{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "proj-openshift-chart.fullname" . }}-ingress
  labels:
    {{- include "proj-openshift-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "proj-openshift-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
{{- end }}